<?php
$labels = array();
$labels['vacation'] = 'Odsotnost';
$labels['autoreply'] = "Vključi odzivnik";
$labels['outofoffice'] = 'Obvestilo o odsotnosti';
$labels['autoreplysubject'] = 'Zadeva samodejnega odziva';
$labels['autoreplymessage'] = 'Sporočilo';
$labels['autoreplybutton'] = 'Shrani';
$labels['mailforward'] = 'Posredivanje sporočil';
$labels['separate_alias'] = 'Več naslovov ločite z vejicami';
$labels['separate_forward'] = 'Več naslovov ločite z vejicami';
$labels['keepcopy'] = 'Obdržite kopijo pprejetega sporočila';
$labels['forwardingaddresses'] = 'Posreduj mail na naslov(e)';
$labels['forward'] = 'Nastavitve posredovanja';
$labels['success_changed'] = 'Spremembe odzivnika so uspešno shranjene';
$labels['failed'] = 'Nastavitev je spodletela!';
$labels['aliases'] = 'Aliasi';
// Button text
$labels['aliasesbutton'] = 'Pridobi aliase';
?>
